// src/views/Blog.vue
<template lang="pug">
  div.blog
    PostItemSmall(v-for="(post, key, index) in posts" :adoc = "post.contents", :index="index", :title='post.name')
</template>

<script>
import { mapGetters, mapActions } from "vuex";
import PostItem from "@/components/PostItem.vue";
import PostItemSmall from "@/components/PostItemSmall.vue";

export default {
  name: "blog",
  components: { PostItem, PostItemSmall },
  computed: {
    ...mapGetters("posts", {
      posts: "posts"
    })
  }
};
</script>

<style scoped lang="sass"></style>

// frontend/src/routes/blog/index.svelte
<script context="module">
  export function preload({ params, query }) {
    return this.fetch(`blog.json`)
      .then(r => r.json())
      .then(posts => {
        return { posts };
      });
  }
</script>

<script>
  import Post from "../../components/Post.svelte";
  export let posts;
</script>

<style>

</style>

<svelte:head>
  <title>Blog - Jeffrey Jose</title>
</svelte:head>

<template lang="pug">
div.blog
  +each('posts as post, index')
    Post(contents='{post.teaserhtml}', slug='{post.slug}', index='{index}')
</template>
