// frontend/src/Background.svelte
<script>
import {writable} from "svelte/store"

let coords = writable({x: 10, y:10})
</script>


<style lang="sass">
svg
  height: 100%
  width: 100%
  position: absolute

circle
  opacity: 0.5

</style>

<svg on:mousemove="{e => coords.set({x:e.clientX, y:e.clientY})}">
  <g id="wrapper">
    <circle r="10" cx="{$coords.x}"  cy="{$coords.y}"  fill="red">
  </g>
</svg>

// src/components/Background.vue
<template lang="pug">

 div#background
    svg(@click="handleClick($event);")
      g#wrapper
         circle(v-for="point in points", r=20, :cx="point.x", :cy="point.y") {{point}}
</template>


<script lang="coffee">

export default {
  name: 'background'
  data: () ->

    data =
      points: [{x: 100, y: 100}, {x: 180, y:300}]

    return data

  methods:
    handleClick: (event) ->
      console.log(event)
      @addCircle(event.clientX, event.clientY)

    addCircle: (x, y) ->
      console.log(@points)
      @points.push({x: x, y: y})
}


</script>

<style scoped lang="sass">

#background svg
  height: 100%;
  width: 100%;
  position: absolute;

circle
  fill: red;

</style>
