// frontend/src/components/Background.svelte
<script>
import { writable } from "svelte/store"
import { spring } from "svelte/motion"

let colors = [
        '#f44336',
        '#E91E63',
        '#9C27B0',
        '#673AB7',
        '#3F51B5',
        '#2196F3',
        '#03A9F4',
        '#00BCD4',
        '#009688',
        '#4CAF50',
        '#8BC34A',
        '#CDDC39',
        '#FFEB3B',
        '#FFC107',
        '#FF9800',
        '#FF5722',
      ]
let circles = []
let clickstart
let duration
function random(min, max) {
  return Math.floor(Math.random()*(parseInt(max)-parseInt(min)+1)+parseInt(min))
}

function addCircle(event) {

  clickstart = true
  duration = 0

  let newCircle = {x: event.clientX, y: event.clientY, r: 1, tx: random(-300, 300), maxr: random(10, 30)}
  circles = [...circles, newCircle]
  //requestAnimationFrame(animate)
}

function clickStopped(event) {
  clickstart = false
  console.log(duration, circles)
}

const animate = timestamp => {

  if (clickstart == true) {
    duration = duration + 1
    circles[circles.length - 1].r = duration
  }

  circles.forEach(function (circle) {
    circle.r = Math.max(circle.r - 1, 0)
  })

  circles = circles
  requestAnimationFrame(animate)
}
//requestAnimationFrame(animate)

</script>


<style lang="sass">
svg
  height: 100%
  width: 100%
  position: absolute

circle
  opacity: 0.5

</style>

<svg
  on:mousedown="{addCircle}"
  on:mouseup="{clickStopped}"
  >
  <g id="wrapper">
    {#each circles as circle, i}
      <circle cx="{circle.x}" cy="{circle.y}" r="{circle.r}" fill="{colors[i % colors.length]}">
      <!--
        <animate attributeName = "r" values = "{circle.r};{circle.maxr};{circle.r}" dur="10s" repeatCount="indefinite"/>
        <animate attributeName = "cx" values = "{circle.x};{circle.x + circle.tx};{circle.x}" dur="10s" repeatCount="indefinite"/>
        -->
      </circle>
    {/each}
  </g>
</svg>

// projects/blog/src/components/Background.vue
<template lang="pug">

 div#background
    svg(
      @mousedown.left="start($event.clientX, $event.clientY)",
      @mouseup="stop",
      @touchstart="start($event.touches[0].clientX, $event.touches[0].clientY)",
      @touchend="stop",
      @touchcancel="stop")
      g#wrapper
         g#test(v-for="point, index in points" :key="index")
           circle(:r="point.r", :cx="point.x", :cy="point.y", :fill="allColors[(index%allColors.length)]")
</template>

<script lang="coffee">

_ = require 'lodash'
{TweenLite, TweenMax} = require 'gsap'

export default {
  name: 'background'
  data: () ->

    data =

      interval: false
      clickDuration: 0

      lastCircle: {}

      duration: 5
      points: []
      defaultColors: [
        '#f44336'
        '#E91E63'
        '#9C27B0'
        '#673AB7'
        '#3F51B5'
        '#2196F3'
        '#03A9F4'
        '#00BCD4'
        '#009688'
        '#4CAF50'
        '#8BC34A'
        '#CDDC39'
        '#FFEB3B'
        '#FFC107'
        '#FF9800'
        '#FF5722'
      ]

    return data

  created: () ->
    window.addEventListener('keyup', @key)
    @allColors = @defaultColors

  methods:

    key: (event) ->
      if event.code is not 'Space'
        return


    start:(x, y) ->

      if not @interval
        @clickDuration = 0
        @addCircle(x, y)
        @interval = setInterval(() =>
                                @clickDuration = @clickDuration + 1
                                @lastCircle.r = @clickDuration
          , 10)
      else
        @updateCircle()

    animate: () ->
      TweenMax.staggerTo(@points, @duration, cycle: {
        x: (index, target) => @wiggle(target.x),
        r: (index, target) => @random(8, 40)
        }, onComplete: @animate)

    stop:() ->

      clearInterval(@interval)
      @interval = false
      @animate()


    wiggle: (val) ->
      v = parseInt(val)

      max = Math.max(0, v-3)
      min = Math.min(100, v+3)

      r = @random(max, min)

      return "#{r}%"

    random: (min, max) ->
      return Math.floor(Math.random()*(parseInt(max)-parseInt(min)+1)+parseInt(min))

    addCircle: (x, y) ->
      @lastCircle = {x:"#{x*100/window.innerWidth}%", y:y, id: Date.now(), r: 0}
      @points.push(@lastCircle)

      @points.ease = Quad.EaseInOut

}
</script>

<style scoped lang="sass">

#background svg
  height: 100%
  width: 100%
  position: absolute

circle
  opacity: 0.5
</style>
